### ISSUE TITLE
Compatibilty updates

### ISSUE THREAD

**Issue by daltonamitchell** [wildland/ember-polymer#4]
Seeing that Polymer and CLI have seen a few upgrades since this was released, are you interested in doing some upgrades to stay compatible? This looks like a great package but I had quite a few issues building.

I'm happy to contribute some PR's this weekend but it'd be good to discuss how you want to handle backward compatibility. CLI 2.* introduced quite a few breaking changes. Any thoughts on how to proceed?

**Comment by Samsinite** [comment]
Yes, both Ember and Polymer have received quite a few upgrades since I last updated this addon. I would love to see this addon be Ember/EmberCLI 2.0 and polymer 1.0 compatible. Any PR's that you are willing to contribute would be much appreciated. Some automated tests to help test compatibility would be useful too, but not required as I'm not sure what they would even look like.

Currently I don't have any thoughts as I haven't attempted to use Polymer for a few months, though it is much more stable now than it was at the time this addon was created.

**Comment by Samsinite** [comment]
Sorry for the late reply, I don't normally receive issue notifications unless I am tagged or previously participated in the comments.

**Comment by daltonamitchell** [comment]
Not a problem @Samsinite, thanks for the work you've done so far! I'll see if I can start digging in this weekend.

**Comment by daltonamitchell** [comment]
Closing this for now, haven't had much time for JS recently. I'm also unsure how the backwards compatibility would work best. These issues might be better handled in individual chunks as I'm sure Ember and Polymer have diifferent concerns related to upgrades/compatibility.

**Comment by Samsinite** [comment]
Sounds good. Not sure when/if I'll get to this as I have other higher priorities at the moment.
